" load ~/dotfiles/vim files
set runtimepath=~/dotfiles/vim,$VIMRUNTIME

" load pathogen
filetype off
source ~/dotfiles/vim/bundle/pathogen/autoload/pathogen.vim
call pathogen#infect('~/dotfiles/vim/bundle')
call pathogen#helptags()


" Enable filetype plugin
filetype plugin indent on

set nocompatible
