#!/bin/bash

declare -a files=(
	"$HOME/.bash_profile.local"
	"$HOME/.dotfiles/shell/bash/exports"
	"$HOME/.dotfiles/shell/common/aliases/aliases"
	"$HOME/.dotfiles/shell/bash/functions"
	"$HOME/.dotfiles/shell/bash/bash_prompt"
)

# If these files are readable, source them
for file in "${files[@]}"; do
	[ -r "$file" ] && source "$file"
done
unset file files

export HISTCONTROL=ignoredups:ignorespace
